### ISSUE TITLE
possible workaround for the new patch afk kick aggressiveness?

### ISSUE THREAD

**Issue by the1trueOG** [Siterizer/new-world-fishing-bot#110]
the new patch has implemented a really aggressive afk kick, im guessing to stop bots. sometimes i get kicked after 5 minutes sometimes after 15 minutes. ive read in various forums that some people genuinely fishing with out botting are getting kicked as well.

**Comment by Siterizer** [comment]
Okay, so there is issue about that: https://github.com/Siterizer/new-world-fishing-bot/issues/107

I won't close this issue, but will leave here my statemet, and disable comments:

i will wait 1-2 days for amazon replay, because you know, it kicks even 'normal' fishers after 15mins
and if they do not fix that then i will create new release with simple movement.
  Btw, thank you for all of your advices even when i don't replay you can be sure i read everything

**Comment by Siterizer** [comment]
New release is here!
https://github.com/Siterizer/new-world-fishing-bot/releases/tag/v1.2.1
