### ISSUE TITLE
unable to initiate fishing

### ISSUE THREAD

**Issue by naynaystarx** [Siterizer/new-world-fishing-bot#178]
hello! i know nuts about coding so i just used it as it is. setting the rectangle in frame and started fishing. able to cast hook, able to click on catching fish, but unable to reel in. always after catching on the fish, it reels one time, then no more, causing the fish to swim away. any help to get it function properly?

also, repair tab will open by itself is it? or how do i do it. thanks and appreciate the help.

**Comment by CJWI86** [comment]
When I had this issue it was caused by the colorblind setting. If that's not it double check everything is as described in the readme then work on shrinking your box, this can make a big difference too. Try to get it to be like a narrow rectangle just from underneath the compass bar to where the shore starts in your fishing spot.
