### ISSUE TITLE
Speed up caught fish animation by left clicking once

### ISSUE THREAD

**Issue by jolamar** [Siterizer/new-world-fishing-bot#198]
Time between catching a fish and casting again is too long. You can skip the animation that occurs once you've caught a fish by left clicking once. Then the wait time can be decreased as well before the next cast.

**Comment by syntax001** [comment]
> It's one of those 80%/20% things; it doesn't work 10-20% of the time but speeds up the process 80-90% which is an overall enhancement if you are fishing for several hours.
> 
> In my testing, the times when it fails is when you initially start casting the rod, then of course the extra click will do a short cast and fail to cast, and then on a repair, it also does it because there is no successful catch state to exit out of.
> 
> My one-line addition is super simple and quick 'n dirty. To make this less error prone, I'd want to keep track of the last_state and then not click when certain conditions are met.
> 
> But overall, I think this is still a good change because my average time per catch went down.
> 
> Let me parse my logfiles and see what the before/after is and I'll update here.

Siterizer is right, even with your method, the bot breaks entirely if it messes up. So its not really an 80/20% thing. Its a 100% guarantee that the bot will break itself, just a matter of when. If people are using this for long periods of time you want it to be very reliable. 

Unless i've completely misunderstood how you did it? From what i understand you just added a mouseclick like so before the cast() function right?

```
    elif result_from_model == '5': #5 - model did not match anything (left click, wait x sec)
        info("Cast fishing rod")
        press_mouse_key()
        release_mouse_key()
        cast()
        return '5'
```

If the bot accidentally skips the delay during reeling, then the bot is in an endless loop of trying to cast the rod, as siterizer said, because of this extra mouseclick.


> When a fish is caught, we get the "SUCCESS" graphic flash, and that should be the only time we want to do a LMC. Is OpenCV fast enough to catch when the "SUCCESS" shows up?

This would also not work, because even if the delay gets skipped by the reeling, the "success" text still shows, bringing us back to the endless casting loop.

Im afraid the only way to do this reliably is to find a keypress that will skip the delay, but not cast the fishing rod. I've tried almost every keybind in the game, but it seems that only left mouse click can skip it :(

**Comment by tallglen** [comment]
I haven't had the endless casting loop happen to me yet.  But if it's happened to you and Siterizer, then it'll probably happen to others.

There is one more thing we can try.  Disarming/arming the fishing rod by hitting F3 twice will also skip the animation.  I'm running both of these methods simultaneously on 2 PCs and have been watching them all day long.   The F3 method is slightly slower than the LMC but not by much.

**Comment by syntax001** [comment]
> I haven't had the endless casting loop happen to me yet. But if it's happened to you and Siterizer, then it'll probably happen to others.
> 
> There is one more thing we can try. Disarming/arming the fishing rod by hitting F3 twice will also skip the animation. I'm running both of these methods simultaneously on 2 PCs and have been watching them all day long. The F3 method is slightly slower than the LMC but not by much.
> 
> The other enhancement I'm testing is keeping track of state so the reset doesn't occur at the wrong time. I don't perform the reset on the 1st cast or after a repair; I try to only do the reset after 'Found a fish' has occurred.

Could you post the code change you made, and your config.yml? I have a hard time believing you havent had that happen if you're doing the same as me and Siterizer. It pretty consistently happens before the first repair, even with long reeling times to minimize the reeling doing the skip.

Disarming with F3 is useless if you're fishing with bait, as you'd have to reapply the bait everytime you skip the delay, making it much much slower. Im assuming most people fish with bait, cause why not :D Its dirt cheap and improves your chances for better fish.

Keeping track of state doesnt really solve the reeling skipping the delay early either, but as i said im interested to see what you've done differently to avoid the endless casting loop.

**Comment by tallglen** [comment]
> Disarming with F3 is useless if you're fishing with bait, as you'd have to reapply the bait everytime you skip the delay, making it much much slower. Im assuming most people fish with bait, cause why not :D Its dirt cheap and improves your chances for better fish.

I wouldnt say it's "useless".  When you're fishing over the course of 10+ hours, you'll run out of bait quickly.  I wanted a more reliable way to reset to the "Ready to Cast" state than using LMC.  I agree that blindly using a LMC is a great way to mess up the loop; it's just a quick 'n dirty solution.

I'm testing matching on the SUCCESS graphic; it doesnt work 100%, either because OpenCV isn't fast enough or something else but when it does work, it correctly cancels the animation.

Since I've made so many changes, I'll fork the repo and then it'll be easier to read.

The other opportunity to eliminate another delay I'd like to take a crack at is the delay between casting and waiting for fish.  There is currently a delay of about 15s between casting and waiting:

```
2021-10-30 08:53:05,452 [INFO] Cast fishing rod
2021-10-30 08:53:19,766 [INFO] Waiting for fish...
```

Should be easy to detect the "ready to cast" state with the icon matching you get at the start of the fishing loop.

As for the endless casting bug, I'd also like to be able to catch these states and then reset the fishing loop.  I've encountered the bug reported by other users where even w/o my enhancements, we'll get stuck at 100% and pause forever, or never cast again.

**Comment by tallglen** [comment]
Forked into:
https://github.com/tallglen/new-world-fishing-bot

This doesn't have the changes to keep track of state; more complicated to keep track of state so going to try this on my main fisherman.  I have the other 2 versions running concurrently just to see if they get into the endless state.

Here's the tests I have running:
1) Fisherman cancelling animation using F3
2) Fisherman cancelling animation using image rec on SUCCESS
3) Fisherman cancelling animation unintelligently by using LMC after reeling in a fish

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
