### ISSUE TITLE
Add unique signatures to avoid EAC signature detection

### ISSUE THREAD

**Issue by MatthewARoy** [Siterizer/new-world-fishing-bot#205]
Would it be possibly to add an uglifier/minifier that shuffles the code to avoid detection?

**Comment by futureproof123** [comment]
@Siterizer ok so I have another idea, what if you run the bot on a virtual desktop / remote desktop, connect to ur 'gaming pc' via teamviewer or anydesk or whatever, and let the bot operate clicking thru the teamviewer / anydesk, that way it appears as if you are just playing the game from a remote location. Would this work ? 
It would also bypass the signature bs because the bot is running on a remote pc.

would this work? anyone have any insight into this
