### ISSUE TITLE
Multithread

### ISSUE THREAD

**Issue by knightmisuto** [Siterizer/new-world-fishing-bot#244]
I saw you new release have added multithreading, im new to progamming but still curios how you do that but seem like your source code not update with release so i cant see what change. Can u please tell me how you can apply multithreading in your code? that will be great help for my study. Thank!

**Comment by jolamar** [comment]
Switch to branch 2.0.0 if you want to run it yourself otherwise download the release. If you really want to know what's under the hood here's the gist:


import threading
import asyncio
...
threading.Thread(daemon=True, target=self.asyncio_event_loop.run_forever).start()
self.asyncio_event_loop.create_task(fishing_loop(self.config), name="fishing_loop")

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support
