### ISSUE TITLE
Some problens and suggestions

### ISSUE THREAD

**Issue by Mpaulo** [Siterizer/new-world-fishing-bot#64]
I tested the bot for a few days and I thank you for the great work

- However, I had a few problems with usability. I've tested several settings trying to make the greenscreen as small as possible, but I still have some lost fishs (only with the most difficult).
We know that rarer fish require a little more work and in most of them the bot fails to catch .
It would be interesting a quicker response to stop the pull when the light turns red, 
I notice that when the red alert appears many times consecutively it keeps pulling until the line breaks.

- Another situation is regarding the throw hook, I understand that it is necessary to randomize the move, but it would be interesting to keep this in a smaller space of difference so that we can configure to get it right fishing spot when it is active

- A suggestion is about Stop Bot, once started I can't stop it, usually the program is unresponsive to clicks so it would be interesting to use a hotkey to start or pause. without the need to click on the button itself.

that's it. I hope you understand my points

**Comment by raphalimam** [comment]
You can cnhange the variation of time for the throw of the hook in the config file, the stop bot problem he alredy know and pretends to fix, but a workaround is to only try to stop the bot while he is in the waiting for fish process, the stop is buggy because the 6 seconds pause betwen fishing, but if the fishing alredy started you can stop it easily, you can also reduce the amount of time pressed for reel, since it starts reeling before the red/brown he will complete the time decided, so you cna change in the config to have less reel time, it cause the boot to reel and stop to reel again more times but it reduces the chance of going straight to the red because it started reeling when was going to get the brown.


long text but thats what I did to be easier to use

**Comment by Siterizer** [comment]
@raphalimam thank you for your replays, especially when I have too little time to visit github :)
